config/routes.rb
get 'projects/:project_id/subtask_settings', to: 'subtask_settings#index', as: 'list_subtask'
get 'projects/:project_id/subtask_settings/show', to: 'subtask_settings#show', as: 'show_subtask'
post 'projects/:project_id/subtask_settings/create', to: 'subtask_settings#create', as: 'create_subtask'
put 'projects/:project_id/subtask_settings/:subtask_id', to: 'subtask_settings#update', as: 'update_subtask'
delete 'projects/:project_id/subtask_settings/:subtask_id', to: 'subtask_settings#destroy', as: 'delete_subtask'

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  unloadable
  belongs_to :project
end

app/controllers/subtask_settings_controller.rb
class SubtaskSettingsController < ApplicationController
  require 'json'
  before_action :find_project, :authorize, only: [:show, :index, :create, :update, :destroy]

  def show
    @trackers = @project.trackers
    @all_trackers = Tracker.all
    @subtasks = Subtask.where(:project_id => @project.id)

    @templates = Hash.new

    if @subtasks.nil? or @project.enabled_module(:issue_templates).nil?
      return
    else
      @all_trackers.map{|tracker| tracker.id}.each do |child|
        @templates[child] = get_templates(child)
      end
    end

    @custom_fields = @project.rolled_up_custom_fields
    if @custom_fields.empty?
      @custom_fields = []
    end
  end
   
  def index
    render :json => Subtask.where(:project_id => @project.id).as_json(:only => [:id, :parent, :child, :auto, :default, :template])
  end

  def create
    subtask = Subtask.new(:project_id => @project.id)
    subtask.parent = params[:parent]
    subtask.child = params[:child]
    subtask.auto = params[:auto]
    subtask.default = params[:default]
    subtask.inheritance = params[:inheritance]
    if subtask.save
      flash[:notice] = l(:notice_successful_create_subtask)
    else
      flash[:error] = l(:notice_fail_create_subtask)
    end
    redirect_back(fallback_location: :back)
  end
  
  def update
    id = params[:subtask_id]
    subtask = Subtask.where(:project_id => @project.id).where(:id => id).first
    subtask.parent = params[:parent]
    subtask.child = params[:child]
    subtask.auto = params[:auto]
    subtask.default = params[:default]
    subtask.inheritance = params[:inheritance]
    subtask.template = params[:template]
    subtask.global = (subtask.template.present? and global_templates(subtask.child).map{|template| template.id}.include? subtask.template)
    subtask.custom_fields = params[:custom_fields].to_json
    if subtask.save
      flash[:notice] = l(:notice_successful_update_subtask)
    else
      flash[:error] = l(:notice_fail_update_subtask)
    end
    redirect_back(fallback_location: :back)
  end
  
  def destroy
    id = params[:subtask_id]
    subtask = Subtask.where(:project_id => @project.id).where(:id => id).first
    if subtask.destroy
      flash[:notice] = l(:notice_successful_delete_subtask)
    else
      flash[:error] = l(:notice_fail_delete_subtask)
    end
    redirect_back(fallback_location: :back)
  end
  
  private
  
  def find_project
    @project = Project.find(params[:project_id])
  end

  def get_templates(trackerId)
    return issue_templates(trackerId)+inherit_templates(trackerId)+global_templates(trackerId)
  end

  def templates_project_setting
    IssueTemplateSetting.find_or_create(@project.id)
  end

  def templates_plugin_setting
    Setting.plugin_redmine_issue_templates
  end

  def apply_all_projects?
    templates_plugin_setting['apply_global_template_to_all_projects'].to_s == 'true'
  end

  def issue_templates(trackerId)
    IssueTemplate.get_templates_for_project_tracker(@project.id, trackerId)
  end

  def inherit_templates(trackerId)
    templates_project_setting.get_inherit_templates(trackerId)
  end

  def global_templates(trackerId)
    return [] if apply_all_projects? && (inherit_templates(trackerId).present? || issue_templates(trackerId).present?)

    project_id = apply_all_projects? ? nil : @project.id
    GlobalIssueTemplate.get_templates_for_project_tracker(project_id, trackerId)
  end
end

app/views/issues/_select_subtasks.html.erb
<% if !issue.project.enabled_module(:subtasks).nil? %>
 <% if issue && issue.tracker_id && !issue.id %>
  <% parent = Tracker.where(:id => issue.tracker_id).first %>
  <% project = Project.find(issue.project_id) %>
  <% allowed_tracker_ids = project.trackers.map{|tracker| tracker.id} %>
  <% subtasks = Subtask.where(:project_id => issue.project_id, :parent => issue.tracker_id, :child => allowed_tracker_ids) %>

  <% while project.parent_id.present? do %>
    <% subtasks += Subtask.where(:project_id =>  project.parent_id, :parent => issue.tracker_id, :child => allowed_tracker_ids, :inheritance => true) %>
    <% project = Project.find(project.parent_id) %>
  <% end %>

  <% if subtasks.first %>
  <%= hidden_field_tag 'issue[new_subtask_ids][]', '' %>
  <p id="subtasks_form">
    <label>Create subtasks</label>
    <span id="subtasks_inputs">
    <% subtasks.each do |subtask| %>
      <% child = Tracker.where(:id => subtask.child).first %>
      <label id="issue_new_subtask_ids_<%= subtask.id %>" class="floating">
      <% if subtask.auto %>
        <%= check_box_tag "issue[new_subtask_ids][]", subtask.id, true, :readonly => true, :disabled => true, "onclick" => "return false;" %>
        <%= child.name %> (required)
      <% else %>
        <%= check_box_tag "issue[new_subtask_ids][]", subtask.id, subtask.default %>
        <%= child.name %>
      <% end %>
      </label>
    <% end %>
    </span>
  </p>
  <% end %>
 <% else %>
  <% parent = Tracker.where(:id => issue.tracker_id).first %>
  <% project = Project.find(issue.project_id) %>
  <% allowed_tracker_ids = project.trackers.map{|tracker| tracker.id} %>
  <% subtasks = Subtask.where(:project_id => issue.project_id, :parent => issue.tracker_id, :child => allowed_tracker_ids) %>

  <% while project.parent_id.present? do %>
    <% subtasks += Subtask.where(:project_id =>  project.parent_id, :parent => issue.tracker_id, :child => allowed_tracker_ids, :inheritance => true) %>
    <% project = Project.find(project.parent_id) %>
  <% end %>

  <% existing = issue.children.map {|child| child.tracker.id } %>
  <% if subtasks.first %>
  <%= hidden_field_tag 'issue[new_subtask_ids][]', '' %>
  <p id="subtasks_form">
    <label>Create new subtasks</label>
    <span id="subtasks_inputs">
    <% subtasks.each do |subtask| %>
      <% child = Tracker.where(:id => subtask.child).first %>
      <% existing_children = existing.count(subtask.child) %>
      <label id="issue_new_subtask_ids_<%= subtask.id %>" class="floating">
      <% existing_children_of_tracker = "(" %>
      <% if subtask.auto %>
        <% existing_children_of_tracker += "required, " %>
      <% end %>

      <% if existing_children == 0 %>
        <% existing_children_of_tracker += "none exist yet)" %>
      <% else %>
        <% existing_children_of_tracker += existing_children.to_s %>
        <% existing_children_of_tracker += " exist" %>
        <% if existing_children == 1 %>
          <% existing_children_of_tracker += "s" %>
        <% end %>
        <% existing_children_of_tracker += " already)" %>
      <% end %>

      <% if existing_children == 0 %>
        <%= check_box_tag "issue[new_subtask_ids][]", subtask.id, subtask.default %>
      <% else %>
        <%= check_box_tag "issue[new_subtask_ids][]", subtask.id, false %>
      <% end %>
      <%= child.name %> <%= existing_children_of_tracker %>
      </label>
    <% end %>
    </span>
  </p>
  <% end %>
 <% end %>
<% end %>

app/views/subtask_settings/show.html.erb
<% if @subtasks.first %>
<span><strong>Subtask creation rules:</strong><span>
<div class="box tabular">
<table>
<% @subtasks.each do |subtask| %>
    <%= form_tag(update_subtask_path(@project, subtask.id), method: :put, class: "tabular") do %>
      <tr>
        <td>
          <div class="box tabular">
          When creating a ticket of tracker
          <%= select_tag(:parent, options_from_collection_for_select(@all_trackers, :id, :name, subtask.parent), {:disabled => true})  %>,
          <%= hidden_field_tag(:parent, subtask.parent) %>
          suggest creation of a subticket of tracker
          <%= select_tag(:child, options_from_collection_for_select(@all_trackers, :id, :name, subtask.child), {:disabled => true}) %>.
          <%= hidden_field_tag(:child, subtask.child) %>
          </div>
        </td>
        <td>
          <div class="box tabular">
            Create subtask by default: <%= check_box_tag(:default, :default, subtask.default) %>
          </div>
        </td>
        <td>
          <div class="box tabular">
            Create subtask by force: <%= check_box_tag(:auto, :auto, subtask.auto) %>
          </div>
        </td>
        <td>
          <div class="box tabular">
            Apply to descendant projects: <%= check_box_tag(:inheritance, :inheritance, subtask.inheritance) %>
          </div>
        </td>
        <td>
          <div class="box tabular">
          <% if !@project.enabled_module(:issue_templates).nil? %>
            <% child_tracker = subtask.child %>
            <% child_templates = @templates[child_tracker] %>
            <% template = child_templates.select{|template| subtask.template == template.id} %>
            <% if template.length == 1 and subtask.global == (template[0].is_a? GlobalIssueTemplate) %>
              <% template_id = subtask.template %>
            <% else %>
              <% template_id = nil %>
            <% end %>
            Apply template to child:
            <%= select_tag(:template, options_from_collection_for_select(child_templates, :id, :title, template_id), {:include_blank => true}) %>
          <% end %>
          </div>
        </td>
        <td>
          <div class="box tabular">
            Inherit custom fields:
            <%= select_tag(:custom_fields, options_from_collection_for_select(@custom_fields, :id, :name, (subtask.custom_fields.nil? ? [] : JSON.parse(subtask.custom_fields))), {:multiple => true}) %>
          </div>
        </td>
        <td>
          <div class="box tabular">
            <%= submit_tag l(:button_update) %>
            <%= link_to l(:button_delete), delete_subtask_path(@project.id, subtask.id), :class => "icon icon-del", :method => :delete, data: {:confirm => l(:text_are_you_sure)} %>
          </div>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>
</div>
<% end %>
<span><strong>Add subtask creation rule:</strong><span>
<%= form_tag(create_subtask_path(@project.id), method: :post, class: "tabular") do %>
<div class="box tabular">
<table>
  <tr>
    <td>
      <div class="box tabular">
        When creating a ticket of tracker
        <%= select_tag(:parent, options_from_collection_for_select(@all_trackers, :id, :name))  %>,
        suggest creation of a subticket of tracker
        <%= select_tag(:child, options_from_collection_for_select(@all_trackers, :id, :name))  %>.
      </div>
    <td>
      <div class="box tabular">
        Create subtask by default: <%= check_box_tag(:default, :default, false) %>
      </div>
    </td>
    <td>
      <div class="box tabular">
        Create subtask by force: <%= check_box_tag(:auto, :auto, false ) %>
      </div>
    </td>
    <td>
      <div class="box tabular">
        Apply to descendant projects: <%= check_box_tag(:inheritance, :inheritance, false) %>
      </div>
    </td>
    <td>
      <%= submit_tag l(:button_add) %>
    </td>
</table>
</div>
<% end %>